# Cloudflare Pages Configuration
# https://developers.cloudflare.com/pages/

# Build settings
BUILD_COMMAND = "npm run build"
BUILD_OUTPUT_DIRECTORY = "dist"
NODE_VERSION = "20"

# Environment variables for production
# Set these in Cloudflare Pages dashboard:
# - MONGO_URI
# - MONGO_DB_NAME
# - OPENAI_API_KEY
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - JWT_SECRET
# - MONGO_DATA_API_URL
# - MONGO_DATA_API_KEY

# Preview deployments
PREVIEW_BRANCH = "develop"

# Custom domains (configure in Cloudflare Pages)
# - tcsnio.pages.dev (automatic)
# - tcsn.io (custom domain)
# - www.tcsn.io (custom domain)

# Functions (serverless)
# Place serverless functions in /functions directory
# They will be automatically deployed

# Headers and redirects
# Configure in /public/_headers and /public/_redirects
