# Production deployment to Cloudflare Pages
# This configuration is used when deploying to pages.cloudflare.com

[build]
command = "pnpm install && pnpm build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
PNPM_VERSION = "8"

# Custom redirects and rules
[[redirects]]
# API routes should go to the worker
from = "/api/*"
to = "https://tcsnio.tcsn.workers.dev/:splat"
status = 200

# SPA fallback - all other routes go to index.html
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff" 
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.workers.dev https://ipapi.co;"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
