name = "tcsnio-api"
main = "src/index.js"
compatibility_date = "2024-09-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV namespaces for data storage
[[kv_namespaces]]
binding = "CACHE"
id = "b37ddf5eb5d44a3e8176e2f94b09c17d"

# D1 Database for more complex queries
[[d1_databases]]
binding = "DB"
database_name = "tcsn-db"
database_id = "79ed74c4-40cd-4e7b-ad63-4528cc28a18d"

[env.production]
name = "tcsnio-api"
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
  { binding = "CACHE", id = "b37ddf5eb5d44a3e8176e2f94b09c17d" }
]
d1_databases = [
  { binding = "DB", database_name = "tcsn-db", database_id = "79ed74c4-40cd-4e7b-ad63-4528cc28a18d" }
]

[env.staging]
name = "tcsnio-api-staging"
vars = { ENVIRONMENT = "staging" }
kv_namespaces = [
  { binding = "CACHE", id = "b37ddf5eb5d44a3e8176e2f94b09c17d" }
]
d1_databases = [
  { binding = "DB", database_name = "tcsn-db", database_id = "79ed74c4-40cd-4e7b-ad63-4528cc28a18d" }
]
